notice:
    qywx:
      msgType: xxx
      corpId: xxx
      corpSecret: xxx
      agentId: xxx

    dingTalk:
      appKey: xxx
      appSecret: xxx
      messageId: xxx
      cursor: xxx
      size: xxx

    feiShu:
      appId: xxx
      appSecret: xxx
